apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ui"
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      ai-services.io/application: {{ .Release.Name }}
      ai-services.io/component: ui
  template:
    metadata:
      labels:
        ai-services.io/application: {{ .Release.Name }}
        ai-services.io/template: {{ .Chart.Name }}
        ai-services.io/component: ui
        ai-services.io/version: {{ default .Chart.AppVersion | quote }}
    spec:
      containers:
        - name: ui
          image: "{{ .Values.ui.image }}"
          resources:
            requests:
              cpu: "50m"
              memory: "512Mi"
            limits:
              cpu: "50m"
              memory: "512Mi"
          env:
            - name: BACKEND_HOST
              value: "backend"
            - name: BACKEND_PORT
              value: "5000"
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
