name: Image Scanner

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      skip-license-scan:
        required: false
        type: boolean
        default: false

env:
  IMAGE_FILE_NAME: image.tar
  TRIVY_SBOM_FILE: trivy.json
  PARLAY_SBOM_FILE: parlay.json
  ICR_REGISTRY: icr.io
  ICR_NAMESPACE: ai-services-cicd

jobs:
  cves:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Build image
        working-directory: ${{ inputs.path }}
        run: |
          make build REGISTRY=${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }}
      
      - name: Save image in file
        run: |
          IMAGE_NAME=$(podman images --format "{{.Repository}}:{{.Tag}}" | grep "${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }}" | head -n 1)
          podman save > ${{ env.IMAGE_FILE_NAME }} $IMAGE_NAME

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          input: ${{ env.IMAGE_FILE_NAME }}
          format: table
          severity: CRITICAL,HIGH,MEDIUM
          exit-code: 1
          ignore-unfixed: true
  
  license:
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip-license-scan }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Build and save ${{ inputs.image-name }} image
        working-directory: ${{ inputs.path }}
        run: |
          make build REGISTRY=${{ env.REGISTRY }}
          IMAGE_NAME=$(podman images --format "{{.Repository}}:{{.Tag}}" | grep "${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }}" | head -n 1)
          podman save > ${{ env.IMAGE_FILE_NAME }} $IMAGE_NAME

      - name: Trivy SBOM scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          input: ${{ inputs.path }}/${{ env.IMAGE_FILE_NAME }}
          format: cyclonedx
          output: ${{ env.TRIVY_SBOM_FILE }}
      
      - name: Enrich trivy SBOM with parlay
        run: |
          mkdir -p $HOME/bin
          wget https://github.com/snyk/parlay/releases/download/v0.6.4/parlay_Linux_x86_64.tar.gz
          tar -xzf parlay_Linux_x86_64.tar.gz
          chmod +x parlay
          mv parlay $HOME/bin
          export PATH=$HOME/bin:$PATH
          parlay --version
          parlay ecosystems enrich ${{ env.TRIVY_SBOM_FILE }} | jq . > ${{ env.PARLAY_SBOM_FILE }}
      
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-json-artifact
          path: |
            ${{ env.TRIVY_SBOM_FILE }}
            ${{ env.PARLAY_SBOM_FILE }}
            
      - name: Run python scripts
        run: python .github/scripts/license_scan.py ${{ env.TRIVY_SBOM_FILE }} ${{ env.PARLAY_SBOM_FILE }}
